### PR TITLE
Cleanly Separate Integration Logic

### PR DESCRIPTION
**Pull request by jmkristian**
This was inspired by Keith Amidon's ideas in the attached documents.

The branch begins with several boring merges from other branches, which are the subject of other pull requests. The interesting part begins with commit e99269451dd7 "Add some integration points."

To view the forms, it's convenient to copy or symlink resources/integration/pacread/* up one directory into resources/integration, and then open form-*.html files using Firefox.

[cleanly-separate-integration-functionality-1.pdf](https://github.com/pack-it-forms/pack-it-forms/files/2843952/cleanly-separate-integration-functionality-1.pdf)
[exlicitly-support-sender-and-receiver-views.pdf](https://github.com/pack-it-forms/pack-it-forms/files/2843955/exlicitly-support-sender-and-receiver-views.pdf)

### CODE REVIEW

**Comment by kamidon** [comment]
@jmkristian, thanks for continuing to try to push this aspect forward when I haven't had any time to focus on it due to other demands. I'll try to at least make one pass through this PR over the weekend.

**Comment by jmkristian** [comment]
To focus on the interesting parts, you might like [this view](https://github.com/jmkristian/pack-it-forms/compare/8d68b23...jmkristian:integration).

**Comment by jmkristian** [comment]
Thanks for the review, Keith. I'll try to act on it later this week. Sorry I'm slow to respond. I've been busy with other things.

**Comment by jmkristian** [comment]
I'm abandoning this pull request and will start fresh in another branch.

**Pull request closed without merging**
