### PR TITLE
Prefer Consolas to monospace

### PR DESCRIPTION
**Pull request by jmkristian**
Michael Fox requested this font. It shows a slash through zero characters, so they don't look like capital 'O'.

### CODE REVIEW

**Comment by kamidon** [comment]
In my testing in Firefox I see Consolas being used in textareas but not in input elements of type text.  I think that was also mentioned in the mailing list discussion. Are you looking at that?

**Comment by jmkristian** [comment]
Yes. I'll update this pull request today.

**Comment by jmkristian** [comment]
Michael Fox recommended monaco and profont as alternatives, because they show zeros with a slash.

**Comment by kamidon** [comment]
Merged manually after fixing up conflicts from merging the font size PR first.

**Pull request closed without merging**
